### PR TITLE
fix(prefix): fix prefix validation regexp

### LINKED ISSUE #399: Special characters in prefix lead to errors
## Expected behavior

It works

## Actual behavior

Get the following error
```
Error: options.prefix is invalid. It should contain the prefix on which forest admin routes should be mounted (i.e. "/api/v1")
    at OptionsValidator.checkOtherOptions (/workspaces/JabRefOnline/node_modules/@forestadmin/agent/dist/builder/utils/options-validator.js:76:19)
    at OptionsValidator.validate (/workspaces/JabRefOnline/node_modules/@forestadmin/agent/dist/builder/utils/options-validator.js:35:26)
    at AgentBuilder.start (/workspaces/JabRefOnline/node_modules/@forestadmin/agent/dist/builder/agent.js:198:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Context

Set `prefix: '_admin'`. After removing the regex check at https://github.com/ForestAdmin/agent-nodejs/blob/4b21ca78a4b46d748c8f853e22490c81e6a6bbd3/packages/agent/src/builder/utils/options-validator.ts#L110 it works well, so I think the regex needs to be modified to allow for `_`.

- Package Version:

### PR DESCRIPTION
**Pull request by jeffladiray**
Close #399

Final decision is the one describe [here](https://developers.google.com/maps/url-encoding) without:
- reserved character 
- `.` that shouldn't be supported in prefix.

`\w` handle `[a-zA-Z0-0_]`, so this should be ok

image

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)
- [ ] Ensure that Types have been updated according to your changes (if needed)

### Security

- [ ] Consider the security impact of the changes made

### CODE REVIEW

File: packages/agent/src/builder/utils/options-validator.ts [hunk 1]
```diff
@@ -107,7 +107,7 @@ export default class OptionsValidator {
   }
 
   private static checkOtherOptions(options: AgentOptions): void {
-    if (typeof options.prefix !== 'string' || !/^[-/a-z]*$/i.test(options.prefix)) {
+    if (typeof options.prefix !== 'string' || !/^[-_/a-z]*$/i.test(options.prefix)) {
```
Comment (ghusse) [inline packages/agent/src/builder/utils/options-validator.ts:110]: Just passing by, I have 2 questions:

- why validating the prefix? What are the things we want to avoid?
- why don't you allow numbers too? I'm pretty sure we can have some other specificities.

Comment (jeffladiray) [reply packages/agent/src/builder/utils/options-validator.ts]: > why validating the prefix? What are the things we want to avoid?

Issue with customer mixin `agentUrl` & `prefix` - preventing their agent to start without any error. Validating beforehand instead of excepting the agent to throw elsewhere seems to be a good idea.

> why don't you allow numbers too? I'm pretty sure we can have some other specificities.

[Good catch](https://developers.google.com/maps/url-encoding), but again I'm still looking the original URI rfc to make sure we didn't miss anything else - that's why the PR is in draft.

File: packages/agent/src/builder/utils/options-validator.ts [hunk 2]
```diff
@@ -107,7 +107,7 @@ export default class OptionsValidator {
   }
 
   private static checkOtherOptions(options: AgentOptions): void {
-    if (typeof options.prefix !== 'string' || !/^[-/a-z]*$/i.test(options.prefix)) {
+    if (typeof options.prefix !== 'string' || !/^[-~/\w]*$/i.test(options.prefix)) {
```
Comment (ghusse) [inline packages/agent/src/builder/utils/options-validator.ts:110]: Is it possible to add unit tests that check that these characters are accepted, and that invalid characters are rejected?

Comment (jeffladiray) [reply packages/agent/src/builder/utils/options-validator.ts:110]: I've just added tests on the `validate` method, specifically on prefix, to avoid testing this private method.

Comment (ghusse) [reply packages/agent/src/builder/utils/options-validator.ts:110]: Perfect 👌

**Review by ghusse — APPROVED** [review]
- ✅&nbsp;Code review
  - ✅&nbsp; Performance concerns
  - ✅&nbsp; Security concerns
  - ✅&nbsp; Use pure functions when possible
  - ✅&nbsp; The PR tackle one subject only
- ✅&nbsp;Automatic tests
  - ✅&nbsp; Unit tests
- ✅&nbsp;Manual tests
- ⚠️&nbsp;PR title

I suggest changing the title to `fix(prefix): allow all possible prefixes as defined in the RFC`

**Comment by tobiasdiez** [comment]
Thanks for the quick fix @jeffladiray!
