### PR TITLE
fix(datasource-customizer): add hasFieldChanged function to handle change hook on this field

### LINKED ISSUE #815: usage of changedField inside smart action handlers does not trigger change hook
## Expected behavior

When I use `changedField` property from the context inside smart action handler, I want the field tested to trigger a change hook.

## Actual behavior

It does not trigger a change hook.

```javascript
.addAction('test', {
  scope: 'Global',
  form: [
    {
      label: 'change',
      type: 'String',
    },
    {
      label: 'to change',
      type: 'String',
      isReadOnly: true,
      value: context => {
        if (context.changedField === 'change') {
          return context.formValues.change;
        }
      },
    },
  ],
  execute: () => {},
})
```
image

## Proposal

Add a `hasFieldChanged` function to handle that.
```javascript
.addAction('test', {
  scope: 'Global',
  form: [
    {
      label: 'change',
      type: 'String',
    },
    {
      label: 'to change',
      type: 'String',
      isReadOnly: true,
      value: context => {
        if (context.hasFieldChanged('change')) {
          return context.formValues.change;
        }
      },
    },
  ],
  execute: () => {},
})
```
image

### PR DESCRIPTION
**Pull request by arnaud-moncel**
fix #815

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

### CODE REVIEW

File: packages/datasource-customizer/src/decorators/actions/context/base.ts [hunk 1]
```diff
@@ -19,11 +19,18 @@ export default class ActionContext<
 > extends CollectionCustomizationContext<S, N> {
   readonly formValues: any; // eslint-disable-line @typescript-eslint/no-explicit-any
   readonly filter: TFilter<S, N>;
+
+  /**
+   * @deprecated use `hasFieldChange` instead. [linked issue](https://github.com/ForestAdmin/agent-nodejs/issues/815).
+   * @todo make it private on the next major version.
+   */
   readonly changedField: string;
```
Comment (ghusse) [inline packages/datasource-customizer/src/decorators/actions/context/base.ts:27]: Can't it be replaced by a getter instead, and keep the same API?

File: packages/datasource-customizer/src/decorators/actions/context/base.ts [hunk 2]
```diff
@@ -50,6 +57,12 @@ export default class ActionContext<
           throw new Error('formValues is readonly');
         },
       });
+
+      this.hasFieldChanged = (fieldName: string) => {
+        used.add(fieldName);
```
Comment (Thenkei) [inline packages/datasource-customizer/src/decorators/actions/context/base.ts:62]: This is an underlying mechanism to only trigger recompute on some field change. Basically, the system is here to say whenever this field (those fields) changes I need to recompute form field values.

All this is done by adding a hook change based on the used computed list of fields (name). It only adds fields that will affect output. 

``` 
return (context.hasFieldChanged('A') || context.hasFieldChanged('B') || context.hasFieldChanged('C')) ? 'True' : 'False';
```
Will watch to field change `[A, B, C]`. If `hasFieldChanged('A')` is true then `used` will be only [A]. Since only a change on A field can change the output value (changes on B or C won't change anything).

``` 
return (context.formValues['A'] || context.formValues.['B] || context.formValues.['C']) ? 'True' : 'False';
```
Same behavior with `formValues[fieldName]`.

**Comment by Thenkei** [comment]
I tested it, it's ok (superbe) for me. 👌

**Review by Thenkei — APPROVED** [review]
- ✅&nbsp;Code review
  - ✅&nbsp; Use pure functions when possible
  - ✅&nbsp; Performance concerns
  - ✅&nbsp; Security concerns
  - ✅&nbsp; The PR tackle one subject only
- ✅&nbsp;Automatic tests
  - ✅&nbsp; Unit tests
  - ✅&nbsp; Integration tests
- ✅&nbsp;Manual tests
- ✅&nbsp;PR title
- ❔&nbsp;PR linked to the clickup task
